repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
            - -i
            - --ignore=E265,E309
            - --max-line-length=100
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: name-tests-test
        files: ^tests/.+\.py$
    -   id: fix-encoding-pragma
    -   id: flake8
        exclude: ^docs
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        args: [
            '--add-import', 'from __future__ import absolute_import',
            '--add-import', 'from __future__ import unicode_literals',
        ]
        files: ^(pyramid_mock_server/|tests/).*\.py$
        language_version: python2.7
