language: python

matrix:
  include:
  - env: TOXENV=py27
  - env: TOXENV=py35
  - env: TOXENV=py36

  - env: TOXENV=docs
  - env: TOXENV=pep8

install:
- "pip install tox coveralls"
script:
- tox -e $TOXENV
after_success:
- coveralls
# Faster runs on container based infrastucture
sudo: false
